'use client';

import {useState} from 'react';

type LookupMethod='printed_qr_token'|'nfc_token'|'member_code'|'card_public_id';
type Member={customer:{public_id?:string;display_name?:string;email?:string};card:{card_public_id:string;status:string};membership:{membership_public_id:string;tier:string;status:string;ends_at:string;available_points:number};eligible_benefits:Array<{benefit_code:string;name:string}>};
type Item={product_code:string;description:string;quantity:number;unit_amount_minor:number};
const emptyItem=():Item=>({product_code:'',description:'',quantity:1,unit_amount_minor:0});

export default function Transactions(){
 const [member,setMember]=useState<Member|null>(null);const [items,setItems]=useState<Item[]>([emptyItem()]);const [points,setPoints]=useState(0);const [result,setResult]=useState('');const [busy,setBusy]=useState(false);
 async function lookup(event:React.FormEvent<HTMLFormElement>){event.preventDefault();setBusy(true);setResult('');setMember(null);const form=new FormData(event.currentTarget);const response=await fetch('/api/backend/members/lookup',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({method:form.get('method') as LookupMethod,value:form.get('identifier')})});const payload=await response.json();setBusy(false);if(!response.ok){setResult(response.status===401?'Sign in from Overview first.':payload.message||'Member lookup failed');return}setMember(payload)}
 async function submit(event:React.FormEvent<HTMLFormElement>){event.preventDefault();if(!member)return;setBusy(true);setResult('');const response=await fetch('/api/backend/transactions',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({idempotency_key:crypto.randomUUID(),branch_id:'BR-PH-0001',membership_id:member.membership.membership_public_id,card_lookup_method:'card_public_id',card_identifier:member.card.card_public_id,type:'SALE',currency_code:'PHP',points_redeemed:points,items})});const payload=await response.json();setBusy(false);setResult(JSON.stringify(payload,null,2));if(response.ok)setMember(current=>current?{...current,membership:{...current.membership,available_points:payload.balance}}:current)}
 function updateItem(index:number,field:keyof Item,value:string){setItems(current=>current.map((item,i)=>i===index?{...item,[field]:field==='product_code'||field==='description'?value:Number(value)}:item))}
 return <><h1>Point of Sale</h1><div className="card"><h2>Identify member</h2><form onSubmit={lookup}><label>Lookup method<select name="method" defaultValue="member_code"><option value="printed_qr_token">QR token</option><option value="nfc_token">NFC token</option><option value="member_code">Member code</option>{process.env.NODE_ENV==='development'&&<option value="card_public_id">Card ID (development)</option>}</select></label><label>Card or member identifier<input name="identifier" required autoComplete="off"/></label><button disabled={busy}>Validate member</button></form></div>{member&&<><div className="card"><h2>Validated customer</h2><p><b>{member.customer.display_name||'Customer'}</b> · {member.customer.email}</p><p>{member.membership.tier} · {member.membership.status} · {member.membership.available_points.toLocaleString()} points</p><p className="muted">Membership {member.membership.membership_public_id} · valid through {new Date(member.membership.ends_at).toLocaleDateString()}</p></div><div className="card"><form onSubmit={submit}><h2>Transaction items</h2>{items.map((item,index)=><div className="item-row" key={index}><label>Product code<input required value={item.product_code} onChange={e=>updateItem(index,'product_code',e.target.value)}/></label><label>Description<input required value={item.description} onChange={e=>updateItem(index,'description',e.target.value)}/></label><label>Quantity<input required type="number" min="1" value={item.quantity} onChange={e=>updateItem(index,'quantity',e.target.value)}/></label><label>Amount (minor units)<input required type="number" min="0" value={item.unit_amount_minor} onChange={e=>updateItem(index,'unit_amount_minor',e.target.value)}/></label></div>)}<button type="button" className="secondary" onClick={()=>setItems(current=>[...current,emptyItem()])}>Add item</button><label>Points to redeem<input type="number" min="0" max={member.membership.available_points} value={points} onChange={e=>setPoints(Number(e.target.value))}/></label><button disabled={busy}>Commit transaction</button></form></div></>}{result&&<div className="card"><pre>{result}</pre></div>}</>;
}
