import { CameraView, useCameraPermissions } from 'expo-camera';
import { StatusBar } from 'expo-status-bar';
import { useEffect, useMemo, useState } from 'react';
import { ActivityIndicator, Alert, Modal, Pressable, SafeAreaView, ScrollView, StyleSheet, Text, TextInput, View } from 'react-native';
import { ApiClient } from './src/api';

const Field=({label,value,onChangeText,secure=false}:{label:string;value:string;onChangeText:(value:string)=>void;secure?:boolean})=><TextInput accessibilityLabel={label} autoCapitalize="none" onChangeText={onChangeText} placeholder={label} secureTextEntry={secure} style={styles.input} value={value}/>;
const Button=({label,onPress,disabled=false}:{label:string;onPress:()=>void;disabled?:boolean})=><Pressable accessibilityRole="button" disabled={disabled} onPress={onPress} style={[styles.button,disabled&&styles.disabled]}><Text style={styles.buttonText}>{label}</Text></Pressable>;

export default function App(){const api=useMemo(()=>new ApiClient(),[]);const[ready,setReady]=useState(false);const[signedIn,setSignedIn]=useState(false);useEffect(()=>{api.restore().then(setSignedIn).finally(()=>setReady(true));},[api]);if(!ready)return <SafeAreaView style={styles.center}><ActivityIndicator/></SafeAreaView>;return <SafeAreaView style={styles.safe}><StatusBar style="dark"/>{signedIn?<StaffHome api={api} onLogout={async()=>{await api.logout();setSignedIn(false);}}/>:<Login api={api} onLogin={()=>setSignedIn(true)}/>}</SafeAreaView>;}
function Login({api,onLogin}:{api:ApiClient;onLogin:()=>void}){const[email,setEmail]=useState('');const[password,setPassword]=useState('');const[busy,setBusy]=useState(false);const submit=async()=>{setBusy(true);try{await api.login(email,password);onLogin();}catch(error){Alert.alert('Sign-in failed',String(error));}finally{setBusy(false);}};return <ScrollView contentContainerStyle={styles.page}><Text style={styles.brand}>AFhomes Staff POS</Text><Text style={styles.title}>Employee sign in</Text><Field label="Email" value={email} onChangeText={setEmail}/><Field label="Password" value={password} onChangeText={setPassword} secure/><Button disabled={busy} label={busy?'Signing in…':'Sign in'} onPress={submit}/></ScrollView>;}
function StaffHome({api,onLogout}:{api:ApiClient;onLogout:()=>void}){const[identifier,setIdentifier]=useState('');const[member,setMember]=useState<any>(null);const[scanner,setScanner]=useState(false);const lookup=async(method:string,value:string)=>{try{setMember(await api.request('/api/v1/members/lookup',{method:'POST',body:{method,value}}));}catch(error){Alert.alert('Member not found',String(error));}};return <ScrollView contentContainerStyle={styles.page} keyboardShouldPersistTaps="handled"><View style={styles.row}><View><Text style={styles.brand}>AFhomes Staff POS</Text><Text style={styles.title}>Identify member</Text></View><Pressable onPress={onLogout}><Text style={styles.link}>Sign out</Text></Pressable></View><Button label="Scan printed QR" onPress={()=>setScanner(true)}/><Field label="Member code" value={identifier} onChangeText={setIdentifier}/><Button label="Enter member code" onPress={()=>lookup('member_code',identifier)}/>{member?<Member api={api} member={member} onUpdated={setMember}/>:null}<Scanner visible={scanner} onClose={()=>setScanner(false)} onValue={value=>{setScanner(false);void lookup('printed_qr_token',value);}}/></ScrollView>;}
function Scanner({visible,onClose,onValue}:{visible:boolean;onClose:()=>void;onValue:(value:string)=>void}){const[permission,requestPermission]=useCameraPermissions();useEffect(()=>{if(visible&&!permission?.granted)void requestPermission();},[visible,permission?.granted,requestPermission]);return <Modal animationType="slide" onRequestClose={onClose} visible={visible}><SafeAreaView style={styles.scanner}><View style={styles.scanHeader}><Text style={styles.scanTitle}>Scan member QR</Text><Pressable onPress={onClose}><Text style={styles.linkLight}>Close</Text></Pressable></View>{permission?.granted?<CameraView barcodeScannerSettings={{barcodeTypes:['qr']}} onBarcodeScanned={({data})=>onValue(data)} style={StyleSheet.absoluteFill}/>:<View style={styles.center}><Text style={styles.light}>Camera permission is required.</Text></View>}</SafeAreaView></Modal>;}
function Member({api,member,onUpdated}:{api:ApiClient;member:any;onUpdated:(member:any)=>void}){const[amount,setAmount]=useState('');const[points,setPoints]=useState('0');const commit=async()=>{try{const result=await api.request('/api/v1/transactions',{method:'POST',body:{idempotency_key:`expo-${Date.now()}`,branch_id:'BR-PH-0001',membership_id:member.membership.membership_public_id,card_lookup_method:'card_public_id',card_identifier:member.card.card_public_id,type:'SALE',currency_code:'PHP',points_redeemed:Number(points)||0,items:[{product_code:'AFHOMES',description:'AFhomes service',quantity:1,unit_amount_minor:Number(amount)||0}]}});onUpdated({...member,membership:{...member.membership,available_points:result.balance}});Alert.alert('Transaction committed',`${result.transaction_public_id}\nBalance: ${result.balance}`);}catch(error){Alert.alert('Transaction failed',String(error));}};return <View style={styles.card}><Text style={styles.title}>{member.customer.display_name??'Customer'}</Text><Text>{member.membership.tier} · {member.membership.status}</Text><Text style={styles.points}>{member.membership.available_points} points</Text><Text>Card: {member.card.status}</Text><Field label="Amount in minor units" value={amount} onChangeText={setAmount}/><Field label="Points to redeem" value={points} onChangeText={setPoints}/><Button label="Commit transaction" onPress={commit}/><Text style={styles.note}>NFC requires an Expo development build; QR scanning works in Expo Go.</Text></View>;}
const styles=StyleSheet.create({safe:{flex:1,backgroundColor:'#f4f8fa'},page:{flexGrow:1,gap:14,padding:24},center:{alignItems:'center',flex:1,justifyContent:'center'},brand:{color:'#176b87',fontSize:18,fontWeight:'800'},title:{color:'#102a43',fontSize:28,fontWeight:'800'},input:{backgroundColor:'#fff',borderColor:'#bcccdc',borderRadius:12,borderWidth:1,padding:14},button:{alignItems:'center',backgroundColor:'#102a43',borderRadius:12,padding:15},disabled:{opacity:.5},buttonText:{color:'#fff',fontWeight:'800'},link:{color:'#176b87',fontWeight:'700'},row:{alignItems:'center',flexDirection:'row',justifyContent:'space-between'},card:{backgroundColor:'#fff',borderRadius:20,gap:12,padding:20},points:{color:'#176b87',fontSize:30,fontWeight:'800'},note:{color:'#627d98',fontSize:12},scanner:{backgroundColor:'#000',flex:1},scanHeader:{flexDirection:'row',justifyContent:'space-between',padding:20,zIndex:2},scanTitle:{color:'#fff',fontSize:20,fontWeight:'800'},linkLight:{color:'#fff',fontWeight:'700'},light:{color:'#fff'}});
