import {BadRequestException,ConflictException,Injectable,NotFoundException} from '@nestjs/common';
import {InjectConnection,InjectModel} from '@nestjs/mongoose';
import {Connection,Model} from 'mongoose';
import * as argon2 from 'argon2';
import {randomBytes} from 'node:crypto';
import {ActivateCardDto,CreateTicketDto,CreateTransactionDto,SellCardDto} from './dto';
import {AuditLog,Branch,Membership,Notification,PointsLedger,SupportTicketHeader,SupportTicketMessage,Tier,TransactionHeader,TransactionItem,VipCard} from './models';
const alphabet='23456789ABCDEFGHJKLMNPQRSTUVWXYZ';
const code=()=>Array.from(randomBytes(10),b=>alphabet[b%alphabet.length]).join('');
const publicId=(prefix:string)=>`${prefix}-PH-${code()}`;
@Injectable() export class BusinessService{
 constructor(@InjectConnection() private db:Connection,@InjectModel(VipCard.name)private cards:Model<VipCard>,@InjectModel(Tier.name)private tiers:Model<Tier>,@InjectModel(Membership.name)private memberships:Model<Membership>,@InjectModel(TransactionHeader.name)private tx:Model<TransactionHeader>,@InjectModel(TransactionItem.name)private items:Model<TransactionItem>,@InjectModel(PointsLedger.name)private ledger:Model<PointsLedger>,@InjectModel(SupportTicketHeader.name)private tickets:Model<SupportTicketHeader>,@InjectModel(SupportTicketMessage.name)private messages:Model<SupportTicketMessage>,@InjectModel(Notification.name)private notices:Model<Notification>,@InjectModel(AuditLog.name)private audits:Model<AuditLog>,@InjectModel(Branch.name)private branches:Model<Branch>){}
 health(){return{api:'ok',database:this.db.readyState===1?'ok':'unavailable',realtime:'polling-fallback',background_jobs:'request-driven',environment:process.env.APP_ENV||'development'}}
 async dashboard(){const [activeMemberships,cards,transactions,openTickets]=await Promise.all([this.memberships.countDocuments({status:'ACTIVE'}),this.cards.countDocuments(),this.tx.countDocuments({status:'COMMITTED'}),this.tickets.countDocuments({status:{$nin:['CLOSED','RESOLVED']}})]);return{activeMemberships,cards,transactions,openTickets}}
 cardsList(){return this.cards.find().select('-activation_code_hash').limit(100).lean()}
 async sell(d:SellCardDto){const card=await this.cards.findOne({card_public_id:d.card_public_id});if(!card)throw new NotFoundException('Card not found');if(!['IN_STOCK','ISSUED'].includes(card.status))throw new ConflictException('Card cannot be sold');if(!await this.tiers.exists({tier_code:d.tier_code,is_active:true}))throw new BadRequestException('Tier not found');const activation=code();card.status='PENDING_ACTIVATION';card.sold_at=new Date();card.activation_code_hash=await argon2.hash(activation);card.activation_expires_at=new Date(Date.now()+72*3600_000);card.activation_attempts=0;card.activation_used=false;await card.save();return{card_public_id:card.card_public_id,member_code:card.member_code,activation_code:activation,expires_at:card.activation_expires_at}}
 async activate(d:ActivateCardDto){const card=await this.cards.findOne({$or:[{card_public_id:d.card_identifier},{printed_qr_token:d.card_identifier},{nfc_token:d.card_identifier},{member_code:d.card_identifier}]});if(!card)throw new NotFoundException('Card not found');if(card.status!=='PENDING_ACTIVATION'||card.is_blocked||card.activation_used)throw new ConflictException('Card cannot be activated');if(!card.activation_expires_at||card.activation_expires_at<new Date()||card.activation_attempts>=5)throw new ConflictException('Activation code expired or locked');if(!card.activation_code_hash||!await argon2.verify(card.activation_code_hash,d.activation_code)){card.activation_attempts++;await card.save();throw new BadRequestException('Invalid activation code')}const now=new Date();const membershipId=publicId('MEM');const membership=await this.memberships.create({membership_public_id:membershipId,customer_id:d.customer_id,tier_code:'BRONZE',status:'ACTIVE',starts_at:now,ends_at:new Date(Date.UTC(now.getUTCFullYear()+1,now.getUTCMonth(),now.getUTCDate())),points_balance:0});Object.assign(card,{customer_id:d.customer_id,membership_id:membershipId,status:'ACTIVE',activated_at:now,expires_at:membership.ends_at,activation_used:true,activation_code_hash:undefined});await card.save();return{card_public_id:card.card_public_id,membership}}
 async transact(d:CreateTransactionDto){const existing=await this.tx.findOne({idempotency_key:d.idempotency_key}).lean();if(existing)return existing;const session=await this.db.startSession();try{let result:unknown;await session.withTransaction(async()=>{const m=await this.memberships.findOne({membership_public_id:d.membership_id,status:'ACTIVE'}).session(session);if(!m||m.ends_at<new Date())throw new BadRequestException('Membership is not active');const amount=d.items.reduce((s,i)=>s+i.quantity*i.unit_amount_minor,0);if(d.points_redeemed>m.points_balance)throw new ConflictException('Insufficient points');const earned=d.type==='SALE'?Math.floor(amount/10000):0,id=publicId('TXN');const [h]=await this.tx.create([{transaction_public_id:id,idempotency_key:d.idempotency_key,branch_id:d.branch_id,customer_id:m.customer_id,membership_id:d.membership_id,type:d.type,amount_minor:amount,currency_code:d.currency_code,points_earned:earned,points_redeemed:d.points_redeemed,status:'COMMITTED',transaction_at:new Date()}],{session});await this.items.insertMany(d.items.map((i,n)=>({transaction_id:id,line_no:n+1,...i,line_amount_minor:i.quantity*i.unit_amount_minor})),{session});const delta=earned-d.points_redeemed;m.points_balance+=delta;await m.save({session});await this.ledger.create([{ledger_public_id:publicId('PTS'),membership_id:d.membership_id,transaction_id:id,points_delta:delta,balance_after:m.points_balance,entry_type:d.type}],{session});await this.notices.create([{recipient_id:m.customer_id,channel:'IN_APP',category:'TRANSACTION',title:'Transaction complete',message:`${id} was committed.`,status:'SENT',sent_at:new Date()}],{session});result={...h.toObject(),items:d.items,balance:m.points_balance}});return result}finally{await session.endSession()}}
 async report(){const [summary,byTier]=await Promise.all([this.tx.aggregate([{$match:{status:'COMMITTED'}},{$group:{_id:'$currency_code',transactions:{$sum:1},amount_minor:{$sum:'$amount_minor'},points_earned:{$sum:'$points_earned'},points_redeemed:{$sum:'$points_redeemed'}}}]),this.memberships.aggregate([{$group:{_id:'$tier_code',count:{$sum:1}}},{$sort:{count:-1}}])]);return{summary,byTier}}
 async createTicket(d:CreateTicketDto){const ticketId=publicId('CS');const ticket=await this.tickets.create({ticket_public_id:ticketId,customer_id:d.customer_id,status:'OPEN',subject:d.subject,priority:'NORMAL'});await this.messages.create({ticket_id:ticketId,author_id:d.customer_id,body:d.message,is_internal:false});return ticket}
 listTickets(){return this.tickets.find().sort({created_at:-1}).lean()}
}
