import { Prop, Schema, SchemaFactory } from '@nestjs/mongoose';
import { HydratedDocument, Schema as MSchema, Types } from 'mongoose';

const opts={timestamps:{createdAt:'created_at',updatedAt:'updated_at'},versionKey:false} as const;
@Schema(opts) export class Country{@Prop({unique:true,index:true}) code!:string;@Prop() name!:string;@Prop() default_currency_code!:string;@Prop() default_locale!:string}
@Schema(opts) export class Currency{@Prop({unique:true}) code!:string;@Prop() name!:string;@Prop() minor_units!:number}
@Schema(opts) export class Branch{@Prop({unique:true,index:true}) branch_public_id!:string;@Prop() name!:string;@Prop() country_code!:string;@Prop() currency_code!:string;@Prop() timezone!:string;@Prop({default:true}) is_active!:boolean}
@Schema(opts) export class Tier{@Prop({unique:true}) tier_code!:string;@Prop() name!:string;@Prop() rank!:number;@Prop() duration_value!:number;@Prop() duration_unit!:string;@Prop({default:true}) is_active!:boolean}
@Schema(opts) export class Benefit{@Prop({unique:true}) benefit_code!:string;@Prop() name!:string;@Prop([String]) tier_codes!:string[];@Prop({default:true}) is_active!:boolean}
@Schema(opts) export class User{@Prop({unique:true,index:true}) public_id!:string;@Prop({unique:true,index:true}) email_normalized!:string;@Prop() display_name!:string;@Prop() password_hash!:string;@Prop([String]) roles!:string[];@Prop({default:true}) is_verified!:boolean;@Prop({default:true}) is_active!:boolean}
@Schema(opts) export class Membership{@Prop({unique:true,index:true}) membership_public_id!:string;@Prop({index:true}) customer_id!:string;@Prop() tier_code!:string;@Prop({index:true}) status!:string;@Prop() starts_at!:Date;@Prop({index:true}) ends_at!:Date;@Prop({default:0}) points_balance!:number}
@Schema(opts) export class VipCard{@Prop({unique:true,index:true}) card_public_id!:string;@Prop({index:true,sparse:true}) customer_id?:string;@Prop({index:true,sparse:true}) membership_id?:string;@Prop({unique:true,index:true}) printed_qr_token!:string;@Prop({unique:true,index:true}) nfc_token!:string;@Prop({unique:true,index:true}) member_code!:string;@Prop({index:true}) status!:string;@Prop({default:false}) is_blocked!:boolean;@Prop() issued_at?:Date;@Prop() sold_at?:Date;@Prop() activated_at?:Date;@Prop() expires_at?:Date;@Prop() activation_code_hash?:string;@Prop() activation_expires_at?:Date;@Prop({default:0}) activation_attempts!:number;@Prop({default:false}) activation_used!:boolean}
@Schema(opts) export class TransactionHeader{@Prop({unique:true,index:true}) transaction_public_id!:string;@Prop({unique:true,index:true}) idempotency_key!:string;@Prop({index:true}) branch_id!:string;@Prop({index:true}) customer_id!:string;@Prop() membership_id!:string;@Prop() type!:string;@Prop() amount_minor!:number;@Prop() currency_code!:string;@Prop() points_earned!:number;@Prop() points_redeemed!:number;@Prop() status!:string;@Prop() transaction_at!:Date;@Prop() reversed_transaction_id?:string}
@Schema(opts) export class TransactionItem{@Prop({index:true}) transaction_id!:string;@Prop() line_no!:number;@Prop() product_code!:string;@Prop() description!:string;@Prop() quantity!:number;@Prop() unit_amount_minor!:number;@Prop() line_amount_minor!:number}
@Schema(opts) export class PointsLedger{@Prop({unique:true,index:true}) ledger_public_id!:string;@Prop({index:true}) membership_id!:string;@Prop() transaction_id!:string;@Prop() points_delta!:number;@Prop() balance_after!:number;@Prop() entry_type!:string}
@Schema(opts) export class AuditLog{@Prop({index:true}) actor_id!:string;@Prop() action!:string;@Prop() entity_type!:string;@Prop() entity_id!:string;@Prop() request_id!:string;@Prop({type:MSchema.Types.Mixed}) metadata!:Record<string,unknown>}
@Schema(opts) export class SupportTicketHeader{@Prop({unique:true,index:true}) ticket_public_id!:string;@Prop({index:true}) customer_id!:string;@Prop({index:true}) status!:string;@Prop() subject!:string;@Prop() priority!:string;@Prop() assigned_to?:string;@Prop() closed_at?:Date}
@Schema(opts) export class SupportTicketMessage{@Prop({index:true}) ticket_id!:string;@Prop() author_id!:string;@Prop() body!:string;@Prop({default:false}) is_internal!:boolean}
@Schema(opts) export class Notification{@Prop({index:true}) recipient_id!:string;@Prop() channel!:string;@Prop() category!:string;@Prop() title!:string;@Prop() message!:string;@Prop({default:'PENDING'}) status!:string;@Prop() read_at?:Date;@Prop() sent_at?:Date}
export const schemas={Country:SchemaFactory.createForClass(Country),Currency:SchemaFactory.createForClass(Currency),Branch:SchemaFactory.createForClass(Branch),Tier:SchemaFactory.createForClass(Tier),Benefit:SchemaFactory.createForClass(Benefit),User:SchemaFactory.createForClass(User),Membership:SchemaFactory.createForClass(Membership),VipCard:SchemaFactory.createForClass(VipCard),TransactionHeader:SchemaFactory.createForClass(TransactionHeader),TransactionItem:SchemaFactory.createForClass(TransactionItem),PointsLedger:SchemaFactory.createForClass(PointsLedger),AuditLog:SchemaFactory.createForClass(AuditLog),SupportTicketHeader:SchemaFactory.createForClass(SupportTicketHeader),SupportTicketMessage:SchemaFactory.createForClass(SupportTicketMessage),Notification:SchemaFactory.createForClass(Notification)};
export type UserDoc=HydratedDocument<User>; export type CardDoc=HydratedDocument<VipCard>;
