import {CameraView,useCameraPermissions} from 'expo-camera';
import {StatusBar} from 'expo-status-bar';
import {useCallback,useEffect,useMemo,useState} from 'react';
import {ActivityIndicator,Alert,Modal,Pressable,SafeAreaView,ScrollView,StyleSheet,Text,TextInput,View} from 'react-native';
import QRCode from 'react-native-qrcode-svg';
import {ApiClient} from './src/api';

type Home={customer:{display_name:string};membership:null|{tier:string;status:string;ends_at:string;available_points:number};card:null|{card_public_id:string;member_code:string;status:string}};
type Transaction={transaction_public_id:string;type:string;amount_minor:number;currency_code:string;points_earned:number;points_redeemed:number;status:string;transaction_at:string};
type Notice={_id:string;title:string;message:string;created_at:string};
type Ticket={ticket_public_id:string;subject:string;status:string;priority:string};
type TicketMessage={_id:string;body:string;created_at:string};
type Tab='card'|'activity'|'support';

function Field({label,value,onChangeText,secure=false,multiline=false}:{label:string;value:string;onChangeText:(value:string)=>void;secure?:boolean;multiline?:boolean}){return <TextInput accessibilityLabel={label} autoCapitalize="none" multiline={multiline} onChangeText={onChangeText} placeholder={label} secureTextEntry={secure} style={[styles.input,multiline&&styles.multiline]} value={value}/>}
function Button({label,onPress,disabled=false,secondary=false}:{label:string;onPress:()=>void;disabled?:boolean;secondary?:boolean}){return <Pressable accessibilityRole="button" disabled={disabled} onPress={onPress} style={[styles.button,secondary&&styles.secondary,disabled&&styles.disabled]}><Text style={[styles.buttonText,secondary&&styles.secondaryText]}>{label}</Text></Pressable>}

export default function App(){const api=useMemo(()=>new ApiClient(),[]);const[ready,setReady]=useState(false);const[signedIn,setSignedIn]=useState(false);useEffect(()=>{api.restore().then(setSignedIn).finally(()=>setReady(true))},[api]);if(!ready)return <SafeAreaView style={styles.center}><ActivityIndicator/></SafeAreaView>;return <SafeAreaView style={styles.safe}><StatusBar style="dark"/>{signedIn?<CustomerArea api={api} onLogout={async()=>{await api.logout();setSignedIn(false)}}/>:<Auth api={api} onAuthenticated={()=>setSignedIn(true)}/>}</SafeAreaView>}

function Auth({api,onAuthenticated}:{api:ApiClient;onAuthenticated:()=>void}){const[mode,setMode]=useState<'login'|'register'|'verify'|'forgot'|'reset'>('login');const[email,setEmail]=useState('');const[name,setName]=useState('');const[password,setPassword]=useState('');const[code,setCode]=useState('');const[busy,setBusy]=useState(false);const submit=async()=>{setBusy(true);try{if(mode==='register'){const result=await api.register(email,name,password);if(result.development_code)setCode(String(result.development_code));setMode('verify')}else if(mode==='verify'){await api.verify(email,code);onAuthenticated()}else if(mode==='forgot'){const result=await api.request('/api/v1/auth/forgot-password',{method:'POST',body:{email},authenticated:false});if(result.development_code)setCode(String(result.development_code));setMode('reset')}else if(mode==='reset'){await api.request('/api/v1/auth/reset-password',{method:'POST',body:{email,code,new_password:password},authenticated:false});Alert.alert('Password updated','Sign in with your new password.');setMode('login')}else{await api.login(email,password);onAuthenticated()}}catch(error){Alert.alert('Unable to continue',String(error))}finally{setBusy(false)}};const title={login:'Welcome back',register:'Create account',verify:'Verify email',forgot:'Reset password',reset:'Choose a new password'}[mode];return <ScrollView contentContainerStyle={styles.page} keyboardShouldPersistTaps="handled"><Text style={styles.brand}>AFhomes VIP</Text><Text style={styles.title}>{title}</Text><Field label="Email" value={email} onChangeText={setEmail}/>{mode==='register'?<Field label="Display name" value={name} onChangeText={setName}/>:null}{mode==='verify'||mode==='reset'?<Field label="Verification code" value={code} onChangeText={setCode}/>:null}{mode==='login'||mode==='register'||mode==='reset'?<Field label={mode==='reset'?'New password':'Password'} value={password} onChangeText={setPassword} secure/>:null}<Button disabled={busy} label={busy?'Please wait…':'Continue'} onPress={submit}/><View style={styles.linkRow}>{mode==='login'?<><Pressable onPress={()=>setMode('register')}><Text style={styles.link}>Create account</Text></Pressable><Pressable onPress={()=>setMode('forgot')}><Text style={styles.link}>Forgot password?</Text></Pressable></>:<Pressable onPress={()=>setMode('login')}><Text style={styles.link}>Back to sign in</Text></Pressable>}</View></ScrollView>}

function CustomerArea({api,onLogout}:{api:ApiClient;onLogout:()=>void}){const[tab,setTab]=useState<Tab>('card');return <View style={styles.safe}><View style={styles.header}><Text style={styles.brand}>AFhomes VIP</Text><Pressable onPress={onLogout}><Text style={styles.link}>Sign out</Text></Pressable></View><View style={styles.tabs}>{(['card','activity','support'] as Tab[]).map(value=><Pressable key={value} onPress={()=>setTab(value)} style={[styles.tab,tab===value&&styles.activeTab]}><Text style={tab===value?styles.activeTabText:styles.tabText}>{value[0].toUpperCase()+value.slice(1)}</Text></Pressable>)}</View>{tab==='card'?<MemberCard api={api}/>:tab==='activity'?<Activity api={api}/>:<Support api={api}/>}</View>}

function MemberCard({api}:{api:ApiClient}){const[home,setHome]=useState<Home|null>(null);const[identifier,setIdentifier]=useState('');const[activationCode,setActivationCode]=useState('');const[scanner,setScanner]=useState(false);const[busy,setBusy]=useState(false);const load=useCallback(async()=>{try{setHome(await api.request('/api/v1/customer/me'))}catch(error){Alert.alert('Unable to load membership',String(error))}},[api]);useEffect(()=>{void load()},[load]);const activate=async()=>{setBusy(true);try{await api.request('/api/v1/cards/activate',{method:'POST',body:{card_identifier:identifier,activation_code:activationCode}});await load()}catch(error){Alert.alert('Activation failed',String(error))}finally{setBusy(false)}};if(!home)return <View style={styles.center}><ActivityIndicator/></View>;const{membership,card}=home;return <ScrollView contentContainerStyle={styles.page}><Text style={styles.subtitle}>Hello, {home.customer.display_name}</Text>{membership?<View style={styles.card}><Text style={styles.title}>{membership.tier} VIP</Text><Text style={styles.points}>{membership.available_points.toLocaleString()} points</Text><Text>{membership.status} · valid until {new Date(membership.ends_at).toLocaleDateString()}</Text>{card?<View style={styles.qr}><QRCode value={card.member_code} size={190}/><Text style={styles.memberCode}>{card.member_code}</Text><Text>{card.card_public_id}</Text><Text style={styles.muted}>{card.status}</Text></View>:null}</View>:<View style={styles.card}><Text style={styles.title}>Activate VIP</Text><Button label="Scan activation QR" onPress={()=>setScanner(true)} secondary/><Field label="QR, NFC, member, or card code" value={identifier} onChangeText={setIdentifier}/><Field label="One-time activation code" value={activationCode} onChangeText={setActivationCode}/><Button disabled={busy||!identifier||!activationCode} label={busy?'Activating…':'Activate card'} onPress={activate}/></View>}<Scanner visible={scanner} onClose={()=>setScanner(false)} onValue={value=>{setIdentifier(value);setScanner(false)}}/></ScrollView>}

function Activity({api}:{api:ApiClient}){const[transactions,setTransactions]=useState<Transaction[]>([]);const[notices,setNotices]=useState<Notice[]>([]);const[loading,setLoading]=useState(true);const load=useCallback(async()=>{setLoading(true);try{const[tx,notifications]=await Promise.all([api.request('/api/v1/customer/transactions'),api.request('/api/v1/customer/notifications')]);setTransactions(tx);setNotices(notifications)}catch(error){Alert.alert('Unable to load activity',String(error))}finally{setLoading(false)}},[api]);useEffect(()=>{void load()},[load]);if(loading)return <View style={styles.center}><ActivityIndicator/></View>;return <ScrollView contentContainerStyle={styles.page}><View style={styles.sectionRow}><Text style={styles.sectionTitle}>Transactions</Text><Pressable onPress={()=>void load()}><Text style={styles.link}>Refresh</Text></Pressable></View>{transactions.length?transactions.map(tx=><View key={tx.transaction_public_id} style={styles.listCard}><Text style={styles.listTitle}>{tx.type} · {(tx.amount_minor/100).toLocaleString(undefined,{style:'currency',currency:tx.currency_code})}</Text><Text>{tx.points_earned?`+${tx.points_earned} earned `:''}{tx.points_redeemed?`-${tx.points_redeemed} redeemed`:''}</Text><Text style={styles.muted}>{new Date(tx.transaction_at).toLocaleString()} · {tx.status}</Text></View>):<Text style={styles.muted}>No transactions yet.</Text>}<Text style={styles.sectionTitle}>Notifications</Text>{notices.length?notices.map(notice=><View key={notice._id} style={styles.listCard}><Text style={styles.listTitle}>{notice.title}</Text><Text>{notice.message}</Text><Text style={styles.muted}>{new Date(notice.created_at).toLocaleString()}</Text></View>):<Text style={styles.muted}>No notifications yet.</Text>}</ScrollView>}

function Support({api}:{api:ApiClient}){const[tickets,setTickets]=useState<Ticket[]>([]);const[selected,setSelected]=useState<Ticket|null>(null);const[messages,setMessages]=useState<TicketMessage[]>([]);const[subject,setSubject]=useState('');const[message,setMessage]=useState('');const[busy,setBusy]=useState(false);const loadTickets=useCallback(async()=>{try{setTickets(await api.request('/api/v1/support/tickets/mine'))}catch(error){Alert.alert('Unable to load support',String(error))}},[api]);useEffect(()=>{void loadTickets()},[loadTickets]);const open=async(ticket:Ticket)=>{setSelected(ticket);try{const detail=await api.request(`/api/v1/support/tickets/${ticket.ticket_public_id}`);setMessages(detail.messages)}catch(error){Alert.alert('Unable to open ticket',String(error))}};const create=async()=>{setBusy(true);try{await api.request('/api/v1/support/tickets',{method:'POST',body:{subject,message}});setSubject('');setMessage('');await loadTickets();Alert.alert('Ticket created')}catch(error){Alert.alert('Unable to create ticket',String(error))}finally{setBusy(false)}};const reply=async()=>{if(!selected)return;setBusy(true);try{await api.request(`/api/v1/support/tickets/${selected.ticket_public_id}/messages`,{method:'POST',body:{message}});setMessage('');await open(selected)}catch(error){Alert.alert('Unable to reply',String(error))}finally{setBusy(false)}};if(selected)return <ScrollView contentContainerStyle={styles.page}><Pressable onPress={()=>{setSelected(null);setMessages([])}}><Text style={styles.link}>← All tickets</Text></Pressable><Text style={styles.sectionTitle}>{selected.subject}</Text><Text style={styles.muted}>{selected.ticket_public_id} · {selected.status} · {selected.priority}</Text>{messages.map(item=><View key={item._id} style={styles.listCard}><Text>{item.body}</Text><Text style={styles.muted}>{new Date(item.created_at).toLocaleString()}</Text></View>)}<Field label="Reply" value={message} onChangeText={setMessage} multiline/><Button disabled={busy||!message.trim()} label="Send reply" onPress={reply}/></ScrollView>;return <ScrollView contentContainerStyle={styles.page}><Text style={styles.sectionTitle}>Customer support</Text><View style={styles.card}><Text style={styles.listTitle}>New ticket</Text><Field label="Subject" value={subject} onChangeText={setSubject}/><Field label="How can we help?" value={message} onChangeText={setMessage} multiline/><Button disabled={busy||subject.trim().length<3||!message.trim()} label="Create ticket" onPress={create}/></View>{tickets.map(ticket=><Pressable key={ticket.ticket_public_id} onPress={()=>void open(ticket)} style={styles.listCard}><Text style={styles.listTitle}>{ticket.subject}</Text><Text>{ticket.status} · {ticket.priority}</Text><Text style={styles.muted}>{ticket.ticket_public_id}</Text></Pressable>)}</ScrollView>}

function Scanner({visible,onClose,onValue}:{visible:boolean;onClose:()=>void;onValue:(value:string)=>void}){const[permission,requestPermission]=useCameraPermissions();useEffect(()=>{if(visible&&!permission?.granted)void requestPermission()},[visible,permission?.granted,requestPermission]);return <Modal animationType="slide" onRequestClose={onClose} visible={visible}><SafeAreaView style={styles.scanner}>{permission?.granted?<CameraView barcodeScannerSettings={{barcodeTypes:['qr']}} onBarcodeScanned={({data})=>onValue(data)} style={StyleSheet.absoluteFill}/>:<View style={styles.center}><Text style={styles.light}>Camera permission is required.</Text></View>}<View style={styles.scanHeader}><Text style={styles.scanTitle}>Scan card QR</Text><Pressable onPress={onClose}><Text style={styles.light}>Close</Text></Pressable></View></SafeAreaView></Modal>}

const styles=StyleSheet.create({safe:{flex:1,backgroundColor:'#f4f8fa'},page:{flexGrow:1,padding:24,gap:14},center:{flex:1,alignItems:'center',justifyContent:'center'},header:{alignItems:'center',flexDirection:'row',justifyContent:'space-between',paddingHorizontal:20,paddingTop:12},brand:{color:'#176b87',fontSize:18,fontWeight:'800'},title:{color:'#102a43',fontSize:28,fontWeight:'800'},sectionTitle:{color:'#102a43',fontSize:22,fontWeight:'800'},listTitle:{color:'#102a43',fontSize:16,fontWeight:'700'},subtitle:{color:'#486581'},muted:{color:'#627d98',fontSize:12},input:{backgroundColor:'#fff',borderColor:'#bcccdc',borderRadius:12,borderWidth:1,padding:14},multiline:{minHeight:90,textAlignVertical:'top'},button:{alignItems:'center',backgroundColor:'#176b87',borderRadius:12,padding:15},secondary:{backgroundColor:'#e6f4f8',borderColor:'#176b87',borderWidth:1},secondaryText:{color:'#176b87'},disabled:{opacity:.5},buttonText:{color:'#fff',fontWeight:'800'},link:{color:'#176b87',fontWeight:'700',paddingVertical:8},linkRow:{flexDirection:'row',justifyContent:'space-between'},card:{backgroundColor:'#fff',borderRadius:20,gap:12,padding:22,shadowColor:'#102a43',shadowOpacity:.08,shadowRadius:12},listCard:{backgroundColor:'#fff',borderRadius:14,gap:5,padding:16},points:{color:'#176b87',fontSize:36,fontWeight:'800'},qr:{alignItems:'center',gap:8,paddingTop:16},memberCode:{fontSize:18,fontWeight:'700',letterSpacing:1},tabs:{flexDirection:'row',gap:6,padding:12},tab:{alignItems:'center',borderRadius:10,flex:1,padding:10},activeTab:{backgroundColor:'#176b87'},tabText:{color:'#486581',fontWeight:'700'},activeTabText:{color:'#fff',fontWeight:'800'},sectionRow:{alignItems:'center',flexDirection:'row',justifyContent:'space-between'},scanner:{backgroundColor:'#000',flex:1},scanHeader:{flexDirection:'row',justifyContent:'space-between',padding:20,zIndex:2},scanTitle:{color:'#fff',fontSize:20,fontWeight:'800'},light:{color:'#fff',fontWeight:'700'}});
