import mongoose from 'mongoose';
import {BusinessService} from '../src/business.service';
import * as domain from '../src/models';

const integration=process.env.TEST_MONGODB_URI?describe:describe.skip;

integration('transaction concurrency (MongoDB replica set)',()=>{
 let service:BusinessService;
 let models:Record<string,mongoose.Model<any>>;

 beforeAll(async()=>{await mongoose.connect(process.env.TEST_MONGODB_URI!);models={};for(const[name,schema]of Object.entries(domain.schemas))models[name]=mongoose.models[name]||mongoose.model(name,schema);await Promise.all(Object.values(models).map(model=>model.createIndexes()));service=new BusinessService(mongoose.connection,models.VipCard,models.Tier,models.Membership,models.TransactionHeader,models.TransactionItem,models.PointsLedger,models.SupportTicketHeader,models.SupportTicketMessage,models.Notification,models.AuditLog,models.Branch,models.User,models.Benefit,models.ProductService,models.RewardRule,models.DynamicQrUse,models.TransactionAuthorization,{} as never)});
 beforeEach(async()=>{await mongoose.connection.db!.dropDatabase();await Promise.all(Object.values(models).map(model=>model.createIndexes()));process.env.DYNAMIC_QR_SECRET='integration-dynamic-qr-secret';await models.Branch.create({branch_public_id:'BR-PH-0001',name:'Test',country_code:'PH',currency_code:'PHP',timezone:'Asia/Manila',is_active:true});await models.ProductService.create({product_code:'TEST',name:'Authoritative test product',kind:'PRODUCT',currency_code:'PHP',unit_amount_minor:10000,branch_ids:[],is_active:true});await models.RewardRule.create({rule_code:'TEST-RULE',name:'Test reward rule',branch_ids:[],tier_codes:[],points_per_amount_minor:10000,minimum_spend_minor:0,max_points_per_transaction:0,step_up_amount_minor:0,is_active:true});await models.User.create({public_id:'EMP-1',email_normalized:'employee@example.com',display_name:'Employee One',password_hash:'unused',roles:['CASHIER'],branch_ids:['BR-PH-0001'],is_verified:true,is_active:true});await models.User.create({public_id:'CUS-1',email_normalized:'customer@example.com',display_name:'Customer One',password_hash:'unused',roles:['CUSTOMER'],branch_ids:[],is_verified:true,is_active:true});await models.Membership.create({membership_public_id:'MEM-1',customer_id:'CUS-1',tier_code:'GOLD',status:'ACTIVE',starts_at:new Date(Date.now()-1000),ends_at:new Date(Date.now()+86400000),points_balance:5000});await models.VipCard.create({card_public_id:'CARD-1',customer_id:'CUS-1',membership_id:'MEM-1',printed_qr_token:'QR-1',nfc_token:'NFC-1',member_code:'CODE-1',status:'ACTIVE',is_blocked:false,activation_attempts:0,activation_used:true})});
 afterAll(async()=>{await mongoose.disconnect()});

 it('allows exactly one of two concurrent 4,000-point redemptions',async()=>{const request=(key:string)=>service.transact({idempotency_key:key,branch_id:'BR-PH-0001',membership_id:'MEM-1',card_lookup_method:'card_public_id',card_identifier:'CARD-1',type:'REDEEM',currency_code:'PHP',points_redeemed:4000,items:[{product_code:'TEST',description:'Concurrent redemption',quantity:1,unit_amount_minor:0}]},'EMP-1');const results=await Promise.allSettled([request('race-1'),request('race-2')]);expect(results.filter(result=>result.status==='fulfilled')).toHaveLength(1);expect(results.filter(result=>result.status==='rejected')).toHaveLength(1);const membership:any=await models.Membership.findOne({membership_public_id:'MEM-1'}).lean();expect(membership.points_balance).toBe(1000);const transactions=await models.TransactionHeader.find({status:'COMMITTED'}).lean();expect(transactions).toHaveLength(1);const ledger=await models.PointsLedger.find({membership_id:'MEM-1'}).lean();expect(ledger).toHaveLength(1);expect(ledger[0]).toEqual(expect.objectContaining({points_delta:-4000,balance_after:1000,entry_type:'REDEEM'}))});

 it('returns the original transaction when identical idempotent requests race and ignores client pricing',async()=>{const request=()=>service.transact({idempotency_key:'same-key',branch_id:'BR-PH-0001',membership_id:'MEM-1',card_lookup_method:'card_public_id',card_identifier:'CARD-1',type:'SALE',currency_code:'PHP',points_redeemed:0,items:[{product_code:'TEST',description:'Forged description',quantity:1,unit_amount_minor:1}]},'EMP-1');const [first,second]=await Promise.all([request(),request()]);expect((first as any).transaction_public_id).toBe((second as any).transaction_public_id);expect((first as any).amount_minor).toBe(10000);expect((first as any).items[0]).toEqual(expect.objectContaining({description:'Authoritative test product',unit_amount_minor:10000}));expect(await models.TransactionHeader.countDocuments({idempotency_key:'same-key'})).toBe(1);expect(await models.PointsLedger.countDocuments({transaction_id:(first as any).transaction_public_id})).toBe(1)});

 it('issues a signed dynamic QR that resolves to the same card',async()=>{const dynamic=await service.customerDynamicQr('CUS-1');expect(dynamic.token).toMatch(/^AFH:DQ:/);const member:any=await service.lookupMember({method:'dynamic_qr_token',value:dynamic.token},'EMP-1');expect(member.card.card_public_id).toBe('CARD-1');expect(member.membership.membership_public_id).toBe('MEM-1')});
});
